# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiCreator/plotdialog.ui'
#
# Created: Thu Jul  9 13:40:40 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_PlotDialog(QtGui.QDialog):
    def __init__(self):
        QtGui.QDialog.__init__(self)
        self.setupUi(self)
    def setupUi(self, baseWidget):
        baseWidget.setObjectName(_fromUtf8("baseWidget"))
        baseWidget.resize(740, 623)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(baseWidget.sizePolicy().hasHeightForWidth())
        baseWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(baseWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.baseLayout = QtGui.QVBoxLayout()
        self.baseLayout.setObjectName(_fromUtf8("baseLayout"))
        self.plotWidget = QtGui.QWidget(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.plotWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        self.verticalLayout_3.addLayout(self.plotLayout)
        self.baseLayout.addWidget(self.plotWidget)
        self.optionsLayout = QtGui.QHBoxLayout()
        self.optionsLayout.setObjectName(_fromUtf8("optionsLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.optionsLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.title_field = QtGui.QLineEdit(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_field.sizePolicy().hasHeightForWidth())
        self.title_field.setSizePolicy(sizePolicy)
        self.title_field.setObjectName(_fromUtf8("title_field"))
        self.gridLayout.addWidget(self.title_field, 2, 0, 1, 1)
        self.unit_label = QtGui.QLabel(baseWidget)
        self.unit_label.setObjectName(_fromUtf8("unit_label"))
        self.gridLayout.addWidget(self.unit_label, 3, 1, 1, 1)
        self.xlabel_field = QtGui.QLineEdit(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xlabel_field.sizePolicy().hasHeightForWidth())
        self.xlabel_field.setSizePolicy(sizePolicy)
        self.xlabel_field.setObjectName(_fromUtf8("xlabel_field"))
        self.gridLayout.addWidget(self.xlabel_field, 0, 0, 1, 1)
        self.yaxis_label = QtGui.QLabel(baseWidget)
        self.yaxis_label.setObjectName(_fromUtf8("yaxis_label"))
        self.gridLayout.addWidget(self.yaxis_label, 1, 1, 1, 1)
        self.unit_field = QtGui.QLineEdit(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit_field.sizePolicy().hasHeightForWidth())
        self.unit_field.setSizePolicy(sizePolicy)
        self.unit_field.setObjectName(_fromUtf8("unit_field"))
        self.gridLayout.addWidget(self.unit_field, 3, 0, 1, 1)
        self.x_axislabel = QtGui.QLabel(baseWidget)
        self.x_axislabel.setObjectName(_fromUtf8("x_axislabel"))
        self.gridLayout.addWidget(self.x_axislabel, 0, 1, 1, 1)
        self.ylabel_field = QtGui.QLineEdit(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ylabel_field.sizePolicy().hasHeightForWidth())
        self.ylabel_field.setSizePolicy(sizePolicy)
        self.ylabel_field.setObjectName(_fromUtf8("ylabel_field"))
        self.gridLayout.addWidget(self.ylabel_field, 1, 0, 1, 1)
        self.activeax_comb = QtGui.QComboBox(baseWidget)
        self.activeax_comb.setObjectName(_fromUtf8("activeax_comb"))
        self.gridLayout.addWidget(self.activeax_comb, 4, 1, 1, 1)
        self.titleaxis_button = QtGui.QPushButton(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleaxis_button.sizePolicy().hasHeightForWidth())
        self.titleaxis_button.setSizePolicy(sizePolicy)
        self.titleaxis_button.setObjectName(_fromUtf8("titleaxis_button"))
        self.gridLayout.addWidget(self.titleaxis_button, 4, 0, 1, 1)
        self.title_label = QtGui.QLabel(baseWidget)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.gridLayout.addWidget(self.title_label, 2, 1, 1, 1)
        self.optionsLayout.addLayout(self.gridLayout)
        self.legend_layout = QtGui.QVBoxLayout()
        self.legend_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.legend_layout.setObjectName(_fromUtf8("legend_layout"))
        self.legend_list = QtGui.QListWidget(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legend_list.sizePolicy().hasHeightForWidth())
        self.legend_list.setSizePolicy(sizePolicy)
        self.legend_list.setObjectName(_fromUtf8("legend_list"))
        self.legend_layout.addWidget(self.legend_list)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.legendedit_field = QtGui.QLineEdit(baseWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendedit_field.sizePolicy().hasHeightForWidth())
        self.legendedit_field.setSizePolicy(sizePolicy)
        self.legendedit_field.setObjectName(_fromUtf8("legendedit_field"))
        self.horizontalLayout.addWidget(self.legendedit_field)
        self.legendedit_button = QtGui.QPushButton(baseWidget)
        self.legendedit_button.setObjectName(_fromUtf8("legendedit_button"))
        self.horizontalLayout.addWidget(self.legendedit_button)
        self.legend_layout.addLayout(self.horizontalLayout)
        self.optionsLayout.addLayout(self.legend_layout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.onefig_cb = QtGui.QCheckBox(baseWidget)
        self.onefig_cb.setObjectName(_fromUtf8("onefig_cb"))
        self.verticalLayout.addWidget(self.onefig_cb)
        self.avgH_cb = QtGui.QCheckBox(baseWidget)
        self.avgH_cb.setObjectName(_fromUtf8("avgH_cb"))
        self.verticalLayout.addWidget(self.avgH_cb)
        self.avgT_cb = QtGui.QCheckBox(baseWidget)
        self.avgT_cb.setObjectName(_fromUtf8("avgT_cb"))
        self.verticalLayout.addWidget(self.avgT_cb)
        self.optionsLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.optionsLayout.addItem(spacerItem1)
        self.baseLayout.addLayout(self.optionsLayout)
        self.verticalLayout_2.addLayout(self.baseLayout)

        self.retranslateUi(baseWidget)
        QtCore.QMetaObject.connectSlotsByName(baseWidget)

    def retranslateUi(self, baseWidget):
        baseWidget.setWindowTitle(_translate("baseWidget", "Dialog", None))
        self.unit_label.setText(_translate("baseWidget", "Unit", None))
        self.yaxis_label.setText(_translate("baseWidget", "y Axis", None))
        self.x_axislabel.setText(_translate("baseWidget", "x Axis", None))
        self.titleaxis_button.setText(_translate("baseWidget", "edit", None))
        self.title_label.setText(_translate("baseWidget", "Title", None))
        self.legendedit_button.setText(_translate("baseWidget", "edit", None))
        self.onefig_cb.setText(_translate("baseWidget", "one figure", None))
        self.avgH_cb.setText(_translate("baseWidget", "average height", None))
        self.avgT_cb.setText(_translate("baseWidget", "average time", None))

